### ISSUE TITLE
Bottom Symbol Cipher 

### ISSUE THREAD

**Issue by Leiton85** [Nodeblue/ASD_50c_Coin#1]
This stands for (ASD) Australian Signals Directorate.
It's at the base of there website as their logo.

See branding also: https://www.cre8ive.com.au/work/asd/

**Comment by Nodeblue** [comment]
Updated to provide additional context. Thanks!

**Comment by MxKnox** [comment]
Found this yesterday afternoon.

Here is an archived picture from that website with the full character set available (bottom row 2nd column).
https://web.archive.org/web/20190313030237im_/https://www.cre8ive.com.au/storage/cache/other5-w1920-q45-cre8ive-1389e.jpeg
You can see from this that there is a method of orienting the cipher so you can see if it is upside down or not.

I can't make out the bottom symbols but I believe they are 0-9.
There is also something about a grid system, but I'm not sure what significance that has. the current version of this on their website leaves this out and has different characters for the typeface example. Maybe the symbols in the new one could have some meaning if decoded.
see: https://www.cre8ive.com.au/storage/cache/asd-revised-w1920-q45-cre8ive-ce5c0.jpeg

The typeface on their website has the top 2 rows upside down.
![image](https://user-images.githubusercontent.com/32785416/188030844-05cf663b-18bb-4f5f-8d87-651ed3cb5746.png)

this is what I worked out on the header on that website too. Probably not useful for anything but they also have multiple rows upside down and some characters that I cannot identify. At this point I don't believe it is of real significance for solving the last code.
![image](https://user-images.githubusercontent.com/32785416/188032162-1f9e93d6-a243-434a-9e9d-a95891cba0f8.png)
