### ISSUE TITLE
A reddit thread to join **Spoiler**

### ISSUE THREAD

**Issue by freman** [Nodeblue/ASD_50c_Coin#2]
Hey,

Just thought I'd mention there's a reddit thread that looks good to join - https://www.reddit.com/r/decipher/comments/wsy7nt/australian_coin_release_decipher_help/

**Comment by Nodeblue** [comment]
Wow, i'm 12 days behind! Thanks for that.

**Comment by StormyKnight17** [comment]
Head Side Braille  
B=C T=B H=F A=A S=E A=D
so as letter counts from A=1 - > B=3 T=2 H=6 A=1 S=5 A=4 
When put in order -> ATBASH
Tail Side 
Bottom Outer Ring -> "FINDCLARITYIN7WIDTHX5DEPTH" using atbash cypher
Outer Ring top -> "WEAREAUDACIOUSINCONCEPTANDMETICULOUSINEXECUTION" using atbash
Inner Ring -> "BELONGINGTOAGREATTEAMSTRIVINGFOREXCELLENCEWEMAKEADIFFERENCEXORHEXA5D75"
Small text code -> "For 75 years the Australian Signals Directorate has brought together people with the skills, adaptability and imagination to operate in the slim area between the difficult and the impossible." - using XOR HEX A5D75 for each 5 digits & then assemble as a single string of text & covert HEX to ASCII. Note: last two digits 8B need to be XOR'ed with just A5 to produce the full stop.
Note A5D75 -> ASD75 -> AUSTRALIAN SIGNALS DIRECTORATE 75 YEARS

**Comment by freman** [comment]
> Wow, i'm 12 days behind! Thanks for that.

I only heard about the whole thing an hour ago.
